### ISSUE TITLE
Question: Julian date corrections

### ISSUE THREAD

**Issue by NaanProphet** [florianmski/SunCalc-Java#2]
So I followed most of the logic `DateUtils` uses to correct for the local timezone offset, but i am thrown off by the `0.5` in the following calculation:

```java
long offset = date.getTimeZone().getOffset(date.getTimeInMillis());
return ((double)date.getTimeInMillis() + offset) / DAY_MS - 0.5 + J1970;
```

Does this imply the correction only works for the timezones +/- 0.5 days, i.e. -12 to +12 GMT?

**Comment by florianmski** [comment]
Was quite some time ago to be honest, the code is based on the js lib of the same name, looking into it this correspond to [this calculus](https://github.com/mourner/suncalc/blob/master/suncalc.js#L29). 
Accordign to Wikipedia:
> The Julian date (JD) of any instant is the Julian day number for the preceding noon in Universal Time plus the fraction of the day since that instant.

Hence the `-0.5`

Some proper testing would really benefit this lib, I'm pretty sure some calculus are off unfortunately :/
A good start would be to port the two first tests [here](https://github.com/mourner/suncalc/blob/master/test.js).

**Comment by NaanProphet** [comment]
Awesome! That would make sense. I'll get cracking on writing more tests :)
